travis:
  secure:
    BINSTAR_TOKEN: cTblvG97kAKaSTTBL+zGhw+fNjSiRgMIGxrdorBxxL9u8qLuFCPXQ1jRVU4yA/424CgTEG/Qev9aluRO93g+wnzW3TYLPGuPaDgFyA7MBJUv+StlP5VBUQ+6REoR7VaVZOsEj/V8/41KejrP0epnQ58Vpt5bCMpE5dGrxRpoUSZlwYEH3nIld7vq+l1nwos3A5OEHuYtD0cd1qYAMJUtTiTohd0FaLEjDu48PMCZdFgCAX/tMIRurf6mSjYG04zALUYcmz2EWRhracc6OHoM4Zr/PYnUbUbJCdqCe66wx7ua58fwsjjYaIJLmNmOUP4WgkpoJ3fmtZTtipsCo94RJ7QST10U+GyjAtSurqin+8RrIjOUoxtgd0w86nwMw5AWpqVSZt7J3Dfy/VX+Tt9+y7pEyGW7S/OBcUaenP3qEcRHESQebIBU7fBsLGz23OvycE8MRd1fV2zd8XZ9SJEJNsuv780ROxoe3ohtFeIJ0BIF46nNKV3ozeNUw3hmGwZ11av6tVzQn0vJ0nrtzA//qnOmKu/6b3qRVE9JTUqRAWOtyjzRuZDRNllTVTIZrXu4SjQhr6aJogHCNu/PcljjAXh1nYfEFolQ5MHAsXVLth0+Rwd/XYmYp+4hW2Bm9MrYWh/Va4wCrlm2Dbup7XXOI3ygkCEpsKleDtAC1KANvic=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
