travis:
  secure:
    BINSTAR_TOKEN: Lv7eCcZ+DBvHiNKPadEcm21yB4ePCQp/OQptMDfiRd/dspt6KFEnjPKLsabr4Fc4EtG8xtGR2pvwstGVtdHulxYUKoIogjHIPVUxe5KBqkBmu9AvD/a/b4/+MoU8uqpu0DBrSN3oUmMw+ZuFlsMJH7fU4lGDyvFL7i7F4xbrtj3Ic33DcMqoPOqEXLnWCF+rfq6gZBUZsm6VprfTeaipQ0PhBlviYAVj5jABH9w/eY3lU7iqYOtEVYzK0h6FpEwOSmAN3NQengsBp41AdASCWsoxoFPjM0AcQeQ9WpOy1DjyuhGGQoe4DraTjvDdshr1olB4me9AtL5RJdj4ALq9ZqvKtcVXNscqdwlM1NiWCilExRDQlDNi6x4copObBbUxEAsxkKv1iqTDFpKL1rGE3WeZ3kMYDtaJpepakYy6pv4VLhfLDcGoKb3Aq5RZ+qORhmL1GTm8KeV967qq1ZEdZeHjPYK3xe0pCJ6Oa23ReQ00Qqk5aFRQJcPlc5gTz7c7ydjEFH160pESMYXs2+G/MzeZPwDGlpzYDh3+WOVZ62p8TI7iMVWxTSL+Ijufcjz9ar3w+dxXzSTwsrrIb2dakTXm/PGPkFqM9WXGgAUkA+tr76EMMEedy8B/P+jVlgj1/1AvB4JHgma5yHlokJUCxgewOkG6RCBRcwlXoj9U3Fk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
